name: Vaspol Ruamviboonsuk
author: Vaspol Ruamviboonsuk
github: 'paivaspol'

url: http://paivaspol.github.io
base: ''

markdown: kramdown
pygments: true
highlighter: rouge

navigation:
  - title: home
    link: index.html
  - title: projects
    link: projects.html
  - title: publications
    link: publications.html
  - title: contact
    link: contact.html
    
